import html
import io
import datetime
from typing import Dict, Any, Optional, List
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.pdfgen import canvas
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    KeepTogether,
)
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle


def _escape(text: Optional[Any]) -> str:
    """Safely escapes text for ReportLab Paragraph XML parsing."""
    if text is None:
        return ""
    s = str(text)
    return html.escape(s, quote=False).replace("\n", "<br/>")


def _format_score(val: Optional[Any]) -> str:
    """Formats numeric or string score with percentage symbol."""
    if val is None or val == "":
        return "N/A"
    if isinstance(val, (int, float)):
        return f"{round(val)}%"
    s = str(val).strip()
    return s if s.endswith("%") else f"{s}%"


def _format_timestamp(dt_str: Optional[str]) -> str:
    """Formats an ISO timestamp into a human-readable recruiter date."""
    if not dt_str:
        return "N/A"
    try:
        dt = datetime.datetime.fromisoformat(dt_str.replace("Z", "+00:00"))
        return dt.strftime("%Y-%m-%d %H:%M %p")
    except Exception:
        return str(dt_str)


class NumberedCanvas(canvas.Canvas):
    """
    Two-pass canvas that computes total page count and renders a running
    header and footer on every page of the dossier.
    """
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states: List[Dict[str, Any]] = []
        self.session_id: str = ""

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_decorations(num_pages)
            super().showPage()
        super().save()

    def draw_page_decorations(self, page_count: int):
        self.saveState()

        # ---------------- Running Header (Top) ----------------
        self.setFont("Helvetica-Bold", 7.5)
        self.setFillColor(colors.HexColor("#0F172A"))
        self.drawString(40, 760, "CANDIDATE TECHNICAL ASSESSMENT DOSSIER")

        if self.session_id:
            self.setFont("Helvetica", 7.5)
            self.setFillColor(colors.HexColor("#64748B"))
            self.drawCentredString(306, 760, f"Session: {self.session_id}")

        self.setFont("Helvetica", 7.5)
        self.setFillColor(colors.HexColor("#64748B"))
        self.drawRightString(572, 760, f"Page {self._pageNumber} of {page_count}")

        # Top rule line
        self.setStrokeColor(colors.HexColor("#CBD5E1"))
        self.setLineWidth(0.5)
        self.line(40, 752, 572, 752)

        # ---------------- Running Footer (Bottom) ----------------
        # Bottom rule line
        self.line(40, 36, 572, 36)

        self.setFont("Helvetica", 7.5)
        self.setFillColor(colors.HexColor("#64748B"))
        self.drawString(40, 24, "Generated by Appz Meeting Observer")
        self.drawRightString(572, 24, "Confidential Hiring Evaluation")

        self.restoreState()


def generate_report_pdf(
    final_report: Dict[str, Any],
    session_id: str,
    candidate_name: Optional[str] = None,
    interviewer: Optional[str] = None,
) -> bytes:
    """
    Generates a professional, recruiter-ready, ATS-style PDF dossier from the
    finalized evaluation report data. Excludes raw transcripts while preserving
    all evaluation rubrics, scores, and question analyses.
    """
    buf = io.BytesIO()

    # Document Geometry: Letter size with 40pt side margins for printable width = 532pt
    doc = SimpleDocTemplate(
        buf,
        pagesize=letter,
        leftMargin=40,
        rightMargin=40,
        topMargin=52,
        bottomMargin=48,
    )

    styles = getSampleStyleSheet()

    # Custom Typography Hierarchy
    style_title = ParagraphStyle(
        "DossierTitle",
        parent=styles["Normal"],
        fontName="Helvetica-Bold",
        fontSize=15,
        leading=19,
        textColor=colors.HexColor("#0F172A"),
        spaceAfter=2,
    )
    style_sub = ParagraphStyle(
        "DossierSub",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=8,
        leading=11,
        textColor=colors.HexColor("#64748B"),
        spaceAfter=8,
    )
    style_sec = ParagraphStyle(
        "SecHeading",
        parent=styles["Normal"],
        fontName="Helvetica-Bold",
        fontSize=9.5,
        leading=13,
        textColor=colors.HexColor("#0F172A"),
        spaceBefore=8,
        spaceAfter=4,
        keepWithNext=True,
    )
    style_body = ParagraphStyle(
        "BodyDark",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=8,
        leading=11,
        textColor=colors.HexColor("#1E293B"),
    )
    style_body_bold = ParagraphStyle(
        "BodyDarkBold",
        parent=styles["Normal"],
        fontName="Helvetica-Bold",
        fontSize=8,
        leading=11,
        textColor=colors.HexColor("#0F172A"),
    )
    style_body_muted = ParagraphStyle(
        "BodyMuted",
        parent=styles["Normal"],
        fontName="Helvetica-Oblique",
        fontSize=7.5,
        leading=10,
        textColor=colors.HexColor("#64748B"),
    )
    style_bullet = ParagraphStyle(
        "BulletEntry",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=8,
        leading=11.5,
        textColor=colors.HexColor("#1E293B"),
        leftIndent=12,
        firstLineIndent=-12,
        spaceAfter=2.5,
    )
    style_kpi_num = ParagraphStyle(
        "KPINumber",
        parent=styles["Normal"],
        fontName="Helvetica-Bold",
        fontSize=19,
        leading=23,
        alignment=1,
        textColor=colors.HexColor("#0F172A"),
    )
    style_kpi_lbl = ParagraphStyle(
        "KPILabel",
        parent=styles["Normal"],
        fontName="Helvetica-Bold",
        fontSize=7,
        leading=9,
        alignment=1,
        textColor=colors.HexColor("#64748B"),
    )

    story: List[Any] = []

    # =========================================================================
    # 1. COVER HEADER & METADATA BLOCK
    # =========================================================================
    story.append(Paragraph("CANDIDATE TECHNICAL ASSESSMENT DOSSIER", style_title))
    story.append(Paragraph("Authoritative evaluation compiled for hiring team review", style_sub))

    status_str = "Verified &amp; Finalized" if final_report.get("is_finalized", True) else "Draft Evaluation"
    eval_date_str = _format_timestamp(final_report.get("evaluated_at"))

    meta_rows = [
        [
            Paragraph(f"<b>Session ID:</b> {_escape(session_id)}", style_body),
            Paragraph(f"<b>Status:</b> <font color=\"#15803D\"><b>{status_str}</b></font>", style_body),
        ],
        [
            Paragraph(f"<b>Finalized:</b> {_escape(eval_date_str)}", style_body),
            Paragraph(f"<b>Candidate Name:</b> {_escape(candidate_name or 'N/A')}", style_body),
        ],
    ]
    if interviewer:
        meta_rows.append([
            Paragraph(f"<b>Interviewer:</b> {_escape(interviewer)}", style_body),
            Paragraph("", style_body),
        ])

    t_meta = Table(meta_rows, colWidths=[310, 222])
    t_meta.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#F8FAFC")),
        ("BOX", (0, 0), (-1, -1), 0.5, colors.HexColor("#CBD5E1")),
        ("INNERGRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#E2E8F0")),
        ("TOPPADDING", (0, 0), (-1, -1), 4.5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4.5),
        ("LEFTPADDING", (0, 0), (-1, -1), 7),
        ("RIGHTPADDING", (0, 0), (-1, -1), 7),
    ]))
    story.append(t_meta)
    story.append(Spacer(1, 8))

    # =========================================================================
    # 2. EXECUTIVE SCORE SUMMARY (KPI Cards)
    # =========================================================================
    story.append(Paragraph("EXECUTIVE SCORE SUMMARY", style_sec))
    overall_score = _format_score(final_report.get("overall_score"))
    qa_avg_score = _format_score(final_report.get("qa_accuracy_average"))
    holistic_dict = final_report.get("holistic_competency") or {}
    holistic_score = _format_score(holistic_dict.get("score"))

    kpi_table_data = [
        [
            Paragraph("OVERALL CANDIDATE SCORE", style_kpi_lbl),
            Paragraph("Q&amp;A ACCURACY AVERAGE", style_kpi_lbl),
            Paragraph("HOLISTIC COMPETENCY", style_kpi_lbl),
        ],
        [
            Paragraph(_escape(overall_score), style_kpi_num),
            Paragraph(_escape(qa_avg_score), style_kpi_num),
            Paragraph(_escape(holistic_score), style_kpi_num),
        ],
    ]
    col_w = 532.0 / 3.0
    t_kpi = Table(kpi_table_data, colWidths=[col_w, col_w, col_w])
    t_kpi.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#F8FAFC")),
        ("BOX", (0, 0), (-1, -1), 0.5, colors.HexColor("#CBD5E1")),
        ("INNERGRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#CBD5E1")),
        ("TOPPADDING", (0, 0), (-1, 0), 5),
        ("BOTTOMPADDING", (0, 0), (-1, 0), 2),
        ("TOPPADDING", (0, 1), (-1, 1), 2),
        ("BOTTOMPADDING", (0, 1), (-1, 1), 6),
    ]))
    story.append(t_kpi)
    story.append(Spacer(1, 8))

    # =========================================================================
    # 3. HOLISTIC COMPETENCY DIMENSIONS
    # =========================================================================
    story.append(Paragraph("HOLISTIC COMPETENCY DIMENSIONS", style_sec))
    dims = holistic_dict.get("dimensions") or {}
    dim_definitions = [
        ("Technical Depth", "technical_depth", "Architectural understanding, depth of core technologies, and systems design"),
        ("Practical Experience", "practical_experience", "Production deployment, real-world troubleshooting, and concrete implementation"),
        ("Problem Solving", "problem_solving", "Algorithmic reasoning, analytical trade-off analysis, and debugging"),
        ("Communication Clarity", "communication_clarity", "Structured articulation, clarity of explanations, and precision"),
    ]
    dim_rows = []
    for d_name, d_key, default_desc in dim_definitions:
        d_obj = dims.get(d_key, {})
        d_score = _format_score(d_obj.get("score"))
        d_summary = d_obj.get("summary") or default_desc
        dim_rows.append([
            Paragraph(f"<b>{_escape(d_name)} &mdash; {_escape(d_score)}</b>", style_body_bold),
            Paragraph(_escape(d_summary), style_body),
        ])

    t_dims = Table(dim_rows, colWidths=[162, 370])
    t_dims.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#FFFFFF")),
        ("BOX", (0, 0), (-1, -1), 0.5, colors.HexColor("#CBD5E1")),
        ("INNERGRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#E2E8F0")),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ("LEFTPADDING", (0, 0), (-1, -1), 6),
        ("RIGHTPADDING", (0, 0), (-1, -1), 6),
    ]))
    story.append(t_dims)
    story.append(Spacer(1, 8))

    # =========================================================================
    # 4. CANDIDATE STRENGTHS
    # =========================================================================
    strengths_elements: List[Any] = [Paragraph("CANDIDATE STRENGTHS", style_sec)]
    strengths = final_report.get("strengths", [])
    if strengths and isinstance(strengths, list) and len(strengths) > 0:
        for s in strengths:
            strengths_elements.append(Paragraph(f"&bull; {_escape(s)}", style_bullet))
    else:
        strengths_elements.append(Paragraph("<i>No specific strengths documented in final evaluation.</i>", style_body_muted))
    strengths_elements.append(Spacer(1, 4))
    story.append(KeepTogether(strengths_elements))

    # =========================================================================
    # 5. DEVELOPMENT AREAS & GAPS
    # =========================================================================
    gaps_elements: List[Any] = [Paragraph("DEVELOPMENT AREAS &amp; GAPS", style_sec)]
    dev_areas = final_report.get("development_areas", [])
    if dev_areas and isinstance(dev_areas, list) and len(dev_areas) > 0:
        for d in dev_areas:
            gaps_elements.append(Paragraph(f"&bull; {_escape(d)}", style_bullet))
    else:
        gaps_elements.append(Paragraph("<i>No development areas highlighted in final evaluation.</i>", style_body_muted))
    gaps_elements.append(Spacer(1, 6))
    story.append(KeepTogether(gaps_elements))

    # =========================================================================
    # 6. JD SKILL REQUIREMENTS MATRIX
    # =========================================================================
    jd_elements: List[Any] = [Paragraph("JD SKILL REQUIREMENTS MATRIX", style_sec)]
    jd_analysis = final_report.get("jd_analysis") or {}
    if jd_analysis.get("summary"):
        jd_elements.append(Paragraph(f"<i>{_escape(jd_analysis['summary'])}</i>", style_body_muted))
        jd_elements.append(Spacer(1, 3))

    cov_skills = jd_analysis.get("covered_skills") or []
    rem_skills = jd_analysis.get("remaining_skills") or []
    cov_content = "<br/>".join([f"&bull; {_escape(s)}" for s in cov_skills]) if cov_skills else "<i>No skills covered</i>"
    rem_content = "<br/>".join([f"&bull; {_escape(s)}" for s in rem_skills]) if rem_skills else "<i>All target skills assessed</i>"

    t_jd = Table([
        [Paragraph("<b>Discussed / Covered</b>", style_body_bold), Paragraph("<b>Remaining / Unassessed</b>", style_body_bold)],
        [Paragraph(cov_content, style_body), Paragraph(rem_content, style_body)],
    ], colWidths=[266, 266])
    t_jd.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#F8FAFC")),
        ("BOX", (0, 0), (-1, -1), 0.5, colors.HexColor("#CBD5E1")),
        ("INNERGRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#E2E8F0")),
        ("TOPPADDING", (0, 0), (-1, -1), 4.5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4.5),
        ("LEFTPADDING", (0, 0), (-1, -1), 6),
        ("RIGHTPADDING", (0, 0), (-1, -1), 6),
    ]))
    jd_elements.append(t_jd)
    jd_elements.append(Spacer(1, 6))
    story.append(KeepTogether(jd_elements))

    # =========================================================================
    # 7. RESUME EXPERIENCE VALIDATION
    # =========================================================================
    res_elements: List[Any] = [Paragraph("RESUME EXPERIENCE VALIDATION", style_sec)]
    resume_val = final_report.get("resume_validation") or {}
    if resume_val.get("summary"):
        res_elements.append(Paragraph(f"<i>{_escape(resume_val['summary'])}</i>", style_body_muted))
        res_elements.append(Spacer(1, 3))

    ver_projs = resume_val.get("verified_projects") or []
    unver_projs = resume_val.get("unverified_projects") or []
    ver_content = "<br/>".join([f"&bull; {_escape(p)}" for p in ver_projs]) if ver_projs else "<i>No projects verified</i>"
    unver_content = "<br/>".join([f"&bull; {_escape(p)}" for p in unver_projs]) if unver_projs else "<i>All documented projects verified</i>"

    t_res = Table([
        [Paragraph("<b>Verified Projects</b>", style_body_bold), Paragraph("<b>Unverified Projects</b>", style_body_bold)],
        [Paragraph(ver_content, style_body), Paragraph(unver_content, style_body)],
    ], colWidths=[266, 266])
    t_res.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#F8FAFC")),
        ("BOX", (0, 0), (-1, -1), 0.5, colors.HexColor("#CBD5E1")),
        ("INNERGRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#E2E8F0")),
        ("TOPPADDING", (0, 0), (-1, -1), 4.5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4.5),
        ("LEFTPADDING", (0, 0), (-1, -1), 6),
        ("RIGHTPADDING", (0, 0), (-1, -1), 6),
    ]))
    res_elements.append(t_res)
    res_elements.append(Spacer(1, 6))
    story.append(KeepTogether(res_elements))

    # =========================================================================
    # 8. CONVERSATION SUMMARY
    # =========================================================================
    conv_elements: List[Any] = [Paragraph("CONVERSATION SUMMARY", style_sec)]
    conv_summary = final_report.get("conversation_summary", "")
    t_conv = Table([[Paragraph(_escape(conv_summary or "No conversation summary recorded."), style_body)]], colWidths=[532])
    t_conv.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#F8FAFC")),
        ("BOX", (0, 0), (-1, -1), 0.5, colors.HexColor("#CBD5E1")),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ("LEFTPADDING", (0, 0), (-1, -1), 8),
        ("RIGHTPADDING", (0, 0), (-1, -1), 8),
    ]))
    conv_elements.append(t_conv)
    conv_elements.append(Spacer(1, 6))
    story.append(KeepTogether(conv_elements))

    # =========================================================================
    # 9. INTERVIEW OBSERVER NOTES
    # =========================================================================
    obs_elements: List[Any] = [Paragraph("INTERVIEW OBSERVER NOTES", style_sec)]
    notes = final_report.get("observer_notes", [])
    if notes and isinstance(notes, list) and len(notes) > 0:
        for n in notes:
            obs_elements.append(Paragraph(f"&bull; {_escape(n)}", style_bullet))
    else:
        obs_elements.append(Paragraph("<i>No observer notes logged during this session.</i>", style_body_muted))
    obs_elements.append(Spacer(1, 8))
    story.append(KeepTogether(obs_elements))

    # =========================================================================
    # 10. DETAILED QUESTION-BY-QUESTION ANALYSIS
    # =========================================================================
    qa_list = final_report.get("question_analysis") or final_report.get("confirmed_qa_pairs") or []
    story.append(Paragraph(f"DETAILED QUESTION-BY-QUESTION ANALYSIS ({len(qa_list)} Confirmed Pairs)", style_sec))

    if not qa_list:
        story.append(Paragraph("<i>No confirmed Q&amp;A pairs recorded for this session.</i>", style_body_muted))
    else:
        for idx, qa in enumerate(qa_list):
            q_num = idx + 1
            acc_score = _format_score(qa.get("accuracy_score"))
            q_text = qa.get("question", "")
            a_text = qa.get("answer", "")
            obs_text = qa.get("observations") or qa.get("notes") or ""
            pair_id = qa.get("pair_id") or qa.get("qa_id") or f"Q{q_num}"

            qa_rows = [
                [
                    Paragraph(f"<b>Question {q_num}</b> <font color=\"#64748B\">({_escape(pair_id)})</font>", style_body_bold),
                    Paragraph(f"<b>Accuracy: {_escape(acc_score)}</b>", ParagraphStyle("AccAlign", parent=style_body_bold, alignment=2)),
                ],
                [
                    Paragraph(f"<b>Question:</b><br/>{_escape(q_text)}", style_body),
                    "",
                ],
                [
                    Paragraph(f"<b>Candidate Response:</b><br/>{_escape(a_text)}", style_body),
                    "",
                ],
            ]
            if obs_text:
                qa_rows.append([
                    Paragraph(f"<b>Evaluation:</b><br/>{_escape(obs_text)}", style_body),
                    "",
                ])

            t_qa = Table(qa_rows, colWidths=[382, 150])
            t_qa.setStyle(TableStyle([
                ("SPAN", (0, 1), (1, 1)),
                ("SPAN", (0, 2), (1, 2)),
                *([("SPAN", (0, 3), (1, 3))] if obs_text else []),
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#F8FAFC")),
                ("BOX", (0, 0), (-1, -1), 0.5, colors.HexColor("#CBD5E1")),
                ("LINEBELOW", (0, 0), (-1, 0), 0.5, colors.HexColor("#CBD5E1")),
                ("TOPPADDING", (0, 0), (-1, -1), 4),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
                ("LEFTPADDING", (0, 0), (-1, -1), 6),
                ("RIGHTPADDING", (0, 0), (-1, -1), 6),
            ]))

            # Keep each Q&A card together on one page if possible
            story.append(KeepTogether([t_qa, Spacer(1, 6)]))

    # Build the document with our NumberedCanvas
    def canvas_factory(*args, **kwargs):
        c = NumberedCanvas(*args, **kwargs)
        c.session_id = session_id
        return c

    doc.build(story, canvasmaker=canvas_factory)
    return buf.getvalue()
