pcm.!default {
    type pulse
    server "unix:/tmp/pulse/native"
}

ctl.!default {
    type pulse
    server "unix:/tmp/pulse/native"
}

pcm.pulse {
    type pulse
    server "unix:/tmp/pulse/native"
}

ctl.pulse {
    type pulse
    server "unix:/tmp/pulse/native"
}
